services:
  postgres:
    image: postgres:17
    container_name: db-barbearia
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yuri1234
      POSTGRES_DB: barbearia
    ports:
      - "5432:5432"
    volumes:
      - barbearia-api:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barbearia"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-barbearia
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: supersecretkey
      DATABASE_URL: postgres://postgres:yuri1234@postgres:5432/barbearia
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  barbearia-api:
